###################################
## RENTAL Endpoints
###################################

### user Create a Rental
POST http://localhost:3000/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMDIsImVtYWlsIjoibWF4bUBnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjE5MTQ3NjcsImV4cCI6MTc2MTkyMTk2N30.i0udotHYUeFilME_DsU4HEo6ZzXMnKWdcujPKMpkPi8
Content-Type: application/json

{
  "carId": 3,
  "customerId": 1002,
  "rentalStartDate": "2025-12-15T00:00:00.000Z",
  "rentalEndDate": "2026-01-20T00:00:00.000Z",
  "totalAmount": 250.00
}


### admin  all Rentals admin
GET http://localhost:3000/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWF4bWlsbGlhbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjE5MTQ5NjgsImV4cCI6MTc2MTkyMjE2OH0.t8MJiLLBvZe7KC3Drt5eTBYOkERhu4WG0uiLHes98hs


### admin Get Rental by ID
GET http://localhost:3000/rental/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWF4bWlsbGlhbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjE5MTQ5NjgsImV4cCI6MTc2MTkyMjE2OH0.t8MJiLLBvZe7KC3Drt5eTBYOkERhu4WG0uiLHes98hs

### Update Rental
PATCH http://localhost:3000/rental/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMDIsImVtYWlsIjoibWF4bUBnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjE5MTQ3NjcsImV4cCI6MTc2MTkyMTk2N30.i0udotHYUeFilME_DsU4HEo6ZzXMnKWdcujPKMpkPi8
Content-Type: application/json

{
  "totalAmount": 300.00
}

### Delete Rental
DELETE http://localhost:3000/rental/1