### Base URL
### http://localhost:3000

##################################
# CAR Endpoints
##################################

###Create a Car

POST http://localhost:3000/cars
Content-Type: application/json

{
  "carModel": "nissans",
  "manufacturer": "Isuzus",
  "year": 2025,
  "color": "black",
  "rentalRate": 50.00,
  "availability": true,
  "locationId": 3
}

#### Get all Cars
GET http://localhost:3000/cars
#
### Get Car by ID
GET http://localhost:3000/cars/1

###  Update Car
 PATCH http://localhost:3000/cars/2
Content-Type: application/json

{
"color": "Red",
"availability": true,
  "locationId": 3
}

### Delete Car
#DELETE http://localhost:3000/car/1
#
###################################
## CUSTOMER Endpoints
###################################
#
###  Create a Customer
POST http://localhost:3000/customer
Content-Type: application/json

{
 "firstName": "John2",
 "lastName": "Doe2",
  "email": "john2.doe@example.com",
  "phoneNumber": "+1234567890",
  "address": "123 Main St, City, State"
}

### Get all Customers

GET http://localhost:3000/customer

### Get Customer by ID
GET http://localhost:3000/customer/2

### Update Customer
PATCH http://localhost:3000/customer/2
Content-Type: application/json

{
"phoneNumber": "+254710795876"
}

### Delete Customer
DELETE http://localhost:3000/customer/1



###################################
## INSURANCE Endpoints
###################################

### Create Insurance
POST http://localhost:3000/insurance
Content-Type: application/json

{
  "carId": 1,
  "policyNumber": "POL123456",
  "startDate": "2025-01-01",
  "endDate": "2026-01-01",
  "insuranceProvider": "Allianz"
}

### Get all Insurance
GET http://localhost:3000/insurance


###Get Insurance by ID
GET http://localhost:3000/insurance/4

### Get Insurance by Car ID
 GET http://localhost:3000/insurance/car/1

### Update Insurance
 PATCH http://localhost:3000/insurance/4
Content-Type: application/json

{
"provider": "AXA"
}

###Delete Insurance
DELETE http://localhost:3000/insurance/1

###################################
## LOCATION Endpoints
###################################
#
### Create Location
POST http://localhost:3000/location
Content-Type: application/json

{
 "locationName": "Downtown Branchs",
  "address": "4567 Center St, City, State",
  "contactNumber": "25"
}

### Get all Locations
GET http://localhost:3000/location

### Get Location by ID
GET http://localhost:3000/location/2

### Update Location
PATCH http://localhost:3000/location/3
Content-Type: application/json

{
"address": "789 New St, City, State"
}

### Delete Location
DELETE http://localhost:3000/location/3


###################################
## MAINTENANCE Endpoints
###################################

### Create Maintenance Record
POST http://localhost:3000/maintenance
Content-Type: application/json

{
  "carId": 1,
  "description": "Oil change",
  "maintenanceDate": "2026-03-01",
  "cost": 50.00
}

### Get all Maintenance Records
GET http://localhost:3000/maintenance

### Get Maintenance by ID
GET http://localhost:3000/maintenance/1

### Get Maintenance by Car ID
GET http://localhost:3000/maintenance/car/1

### Update Maintenance
PATCH http://localhost:3000/maintenance/1
Content-Type: application/json

{
"cost": 55.00
}

####  Delete Maintenance
DELETE http://localhost:3000/maintenance/1
